name: tele_flicks

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #     sdk: flutter
  #a
  #b
  bloc_concurrency: ^0.2.5

  #c
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  
  #d
  dio: ^5.4.3+1

  #e
  equatable: ^2.0.5

  #f
  flutter_bloc: ^8.1.5
  flutter_localization: ^0.2.0
  
  #g
  go_router: ^13.2.4
  get_it: ^7.7.0

  #h
  hydrated_bloc: ^9.1.5

  #i
  # intl: ^0.19.0
  
  #j
  #k
  #l
  #m
  #n
  #o
  #p
  path_provider: ^2.1.3
  player_api:
    path: packages/player_api  

  #q
  #r
  #s
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  
  #t
  #u
  #v
  #w
  web: ^0.5.1
  #x
  #y
  #z



  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_intl: 
  enabled: true
  output_dir: lib/src/common/local/generated
  arb_dir: assets/l10n