name: tele_flicks

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #a
  #b
  bloc_concurrency: ^0.2.5

  #c
  cupertino_icons: ^1.0.8

  #d
  dio: ^5.4.3+1

  #e
  equatable: ^2.0.5

  #f
  flutter_bloc: ^8.1.5

  #g
  go_router: ^13.2.4
  get_it: ^7.7.0

  #h
  hydrated_bloc: ^9.1.5

  #i
  intl: ^0.19.0
  #j
  #k
  #l
  #m
  #n
  #o
  #p
  path_provider: ^2.1.3

  #q
  #r
  #s
  shared_preferences: ^2.2.3

  #t
  #u
  #v
  #w
  web: ^0.5.1
  #x
  #y
  #z

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

  
flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl: 
  enabled: true
  output_dir: lib/src/common/local/generated
  arb_dir: assets/l10n